# Generated by Django 4.2 on 2024-05-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
